export default {
  ADD_TODO: 'ADD_TODO',
  DELETE_TODO: 'DELETE_TODO',
  EDIT_TODO: 'EDIT_TODO',
  COMPLETE_TODO: 'COMPLETE_TODO',
  COMPLETE_ALL: 'COMPLETE_ALL',
  CLEAR_COMPLETED: 'CLEAR_COMPLETED',
  SHOW_ALL: 'show_all',
  SHOW_COMPLETED: 'show_completed',
  SHOW_ACTIVE: 'show_active'
}
