export default {
  ADD_TODO: 'ADD_TODO',
  DELETE_TODO: 'DELETE_TODO',
  COMPLETE_TODO: 'COMPLETE_TODO',
  COMPLETE_TODOS: 'COMPLETE_TODOS',
  CLEAR_COMPLETED: 'CLEAR_COMPLETED',
  TODOS_ORDER: 'TODOS_ORDER',
}
